In [2]:
import numpy as np

A = [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12],
     [13,14,15,16]]

arr = np.asarray(A)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [7]:
#TH1 
print ("Whole array : \n", arr)
print ("\nFirst row : \n", arr[0,:])
print ("\nSecond row : \n", arr[1,:])
print ("\nThird column : \n", arr[:,2])


Whole array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First row : 
 [1 2 3 4]

Second row : 
 [5 6 7 8]

Third column : 
 [ 3  7 11 15]
